# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts --production=false

# Copy source files
COPY linear-issues-mcp-server.js .

# Ensure executable
RUN chmod +x linear-issues-mcp-server.js

# Use a non-root user for safer defaults
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

# Set working dir
WORKDIR /app

# Default command (will be overridden by MCP startCommand)
CMD ["node", "linear-issues-mcp-server.js"]
